name: dokan_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.4
  fluttertoast: ^8.2.5
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.2
  loader_overlay: ^4.0.0
  cached_network_image: ^3.3.1
  flutter_pannable_rating_bar: ^2.7.2+1
  dotted_border: ^2.1.0
  skeletonizer: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  web: false
  image: "assets/icons/png/splash_logo.png"
  color: "#F8F8F8"
  color_dark: "#F8F8F8"
  image_dark: "assets/icons/png/splash_logo.png"

  android_12:
    image: "assets/icons/png/splash_logo_android12.png"
    icon_background_color: "#F8F8F8"
    image_dark: "assets/icons/png/splash_logo_android12.png"
    icon_background_color_dark: "#F8F8F8"
    color: "#F8F8F8"
    color_dark: "#F8F8F8"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/svg/
    - assets/icons/png/
    - assets/json/
    - .env.development
    - .env.production

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
